### PR TITLE
Basic Announcements

### PR DESCRIPTION
**Pull request by ajm188**
Look, I did a thing!

Adds a couple of things:
- Announcements controller to show a list of announcements
- Abstraction for Announcement objects
- HTTPHelper to send get requests that look less ugly
- JSONHelper to parse serialized JSON

It even sort of works! It totally connects to the rails server I have running and gets the announcement objects correctly. Only problem is the view looks sort of cut off (the top part of the table view looks cut off on my simulator), and I'm not sure how to fix it. Appreciate input from @gleichsnerd .

### CODE REVIEW

**Comment by gleichsnerd** [comment]
I'm going to fix this up tonight with the whole swift stuff and then we'll be good to go.

**Comment by gleichsnerd** [comment]
👍

**Comment by gleichsnerd** [comment]
Knowing that this pull request may one day be merged, it fills you with determination!
(I'm going to go ahead and merge this sucker)

**Comment by ajm188** [comment]
RIP my merge commit :frowning:

**Comment by gleichsnerd** [comment]
3slow5me
Better luck next time 😉

**Pull request merged**
